name: Java CI

on: 
   pull_request: {}
   push:
     branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
    matrix:
    java: [8, 11]

    steps:
      - uses: actions/checkout@v2
      - name: Setting JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
